on:
  workflow_dispatch:
    inputs:
      titleText:
        description: "Which text should it say?"
        required: true
        default: "Welcome to Remotion"
      titleColor:
        description: "Which color should it be in?"
        required: true
        default: "black"
name: Create audio
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: docker pull "synesthesiam/coqui-tts:latest"
      - run: npm i
      - run: npm run tts
      - uses: actions/upload-artifact@v2
        with:
          name: t1.wav
          path: audio/t1.wav
