on:
  workflow_dispatch:
    inputs:
      titleText:
        description: "Which text should it say?"
        required: true
        default: "Welcome to Remotion"
      titleColor:
        description: "Which color should it be in?"
        required: true
        default: "black"
name: Test Audio
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: docker pull "synesthesiam/coqui-tts:0.0.13.2"
      - run: npm i
      - run: npm run tts
      - run: docker run -e "HOME=${HOME}" -v "$HOME:${HOME}" -w "${PWD}" --user "$(id -u):$(id -g)" "synesthesiam/coqui-tts:latest" --text "Social commerce platform DealShare has raised $144 million, at a valuation of $455 million led by New York venture fund Tiger Global" --out_path $HOME/t0.wav
      - run: ls audio
      - uses: actions/upload-artifact@v2
        with:
          name: t0.wav
          path: audio/t0.wav
